// Name: Nanako Chung
// Date: Feb 7th, 2017
// Description: I created a program that allows for the user to guess a number and see if it matches the random number generated by the computer

// allows for the use of Scanner class
import java.util.Scanner;

public class GuessTheNumber {

	public static void main(String[] args) {
		// calls the Scanner method
		Scanner input = new Scanner(System.in);

		// chooses a random integer between 0 and 9 using the Math method
		int randomnum = (int)(Math.random()*10);

		// asks the user to guess a number and stores that input into the variable 'guess'
		System.out.print("Guess a number between 0 and 9: ");
		int guess = input.nextInt();

		// if the guess is within 0 and 9 (inclusive), then proceed with comparing the guess to the randomly generated #
		if ((guess>=0)&&(guess<=9)) {
			
			// if the guessed number is the same as the randomly generated number, display to the user the guess was correct
			if (guess==randomnum) {
				System.out.println("Your guess is correct! The number is "+randomnum);

			// likewise, if the guess is higher, display this result to the user
			} else if (guess>randomnum) {
				System.out.println("Too high. Number was "+randomnum);

			// lastly, if the guess is lesser, display this result to the user
			} else if (guess<randomnum) {
				System.out.println("Too low. Number was "+randomnum); }
		
		// if the guess is beyond 9 and below 0 (exclusive), display to the user that the guess was invalid
		} else
			System.out.println("Not a valid guess");
	}
}
